name: go_trike
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.6.1
  location: ^5.0.3
  http: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  geolocator: ^9.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/home.svg
    - assets/icons/description.svg
    - assets/icons/person.svg
    - assets/icons/settings.svg
    - assets/icons/edit.svg
    - assets/icons/help.svg
    - assets/icons/place.svg
    - assets/icons/terminal.png
    - assets/icons/fullscreen.svg
    - assets/icons/person_search.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700